services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.24
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - ./mysql-volume:/var/lib/mysql:rw
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
